nelmio_api_doc:
    name: "IMIE Crafting Application Programming Interface"
    sandbox:
        enabled:  true              # default is `true`, you can set this parameter to `false`
                                    # to disable the sandbox
        accept_type: application/json           # default is `~` (`null`), if set, the value is
                                                # automatically populated as the `Accept` header
        body_format:
            formats: [ form, json ]             # array of enabled body formats,
            default_format: form                # default is `form`, determines whether to send
        request_format:
            formats:                            # default is `json` and `xml`,
                json: application/json          # override to add custom formats or disable
                xml: application/xml            # the default formats
            method: format_param    # default is `format_param`, alternately `accept_header`,
                                    # decides how to request the response format
            default_format: json    # default is `json`