imie_crafting:
    resource: "@IMIECraftingBundle/Resources/config/routing.yml"
    prefix:   /

imie_crafting_rest:
    type: rest
    resource: "@IMIECraftingBundle/Resources/config/routing_rest.yml"
    prefix: /api
    
imie_crafting_jsonrpc:
    resource: "@Wa72JsonRpcBundle/Resources/config/routing.yml"
    prefix:   /rpc

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
